import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import api from '../auth/axios'
import axios from 'axios'
import PropertyVip from '../components/PropertyVip'
import PropertySection from '../components/PropertySection'
import {MDBContainer} from 'mdbreact'
import Carousel from '../components/Carousel'
import Features from '../components/Features'

export default function Home({propertiesVip, properties}) {

  //console.log(process.env.NEXT_PUBLIC_BASE_URL);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel />
      <MDBContainer>
          <PropertyVip propertiesVip={propertiesVip}/>
      </MDBContainer>
      <MDBContainer>
          <PropertySection properties={properties}/>
      </MDBContainer>
      <Features />
    </div>
  )
}

export const getStaticProps = async () => {
  const url = 'https://aqueous-meadow-07678.herokuapp.com/api/properties/vip'
  const {data: propertiesVip} = await axios.get(url);
  //const {data: propertiesVip} = await api.get('/api/properties/vip');
  const url2 = 'https://aqueous-meadow-07678.herokuapp.com/api/properties?limit=6'
  const {data} = await axios.get(url2);
  const properties = data.data;
  return {
    props: {
      propertiesVip,
      properties
    }
  }
}